### ISSUE TITLE
Cant compile LwTxTest

### ISSUE THREAD

**Issue by Farstucker** [roberttidey/LightwaveRF#7]
Hi

I compiled and uploaded LwRxTest, used my siemens remote and got some HEX number in the serial monitor. 

When i open LwTxTest and put the code into "byte msg[] = { ... }" i get an error compiling it, saying that the letters were not declared in the scope.

I am trying to build a LightwaveRF receiver so any help would be greatly appreciated!

Thanks

Will

**Comment by roberttidey** [comment]
LwRxTest prints out messages received as a hex string.

LwTxTest has the byte msg[] place to put the test message in but by default you would enter the decimal equivalents of those numbers, If you want to put in the hex digits then you would need to precede each one with 0x. So if you wanted to transmit a hex A then either put 10 or put 0xA

**Comment by Farstucker** [comment]
Thank you!
